### ISSUE TITLE
Unsafe update operations on replicated vectors

### ISSUE THREAD

**Issue by mihaimaruseac** [haskell/vector#166]
Consider this small program:

```haskell
import Control.Monad
import Control.Monad.ST (runST)

import qualified Data.Vector as V
import qualified Data.Vector.Mutable as VM
import qualified Data.Vector.Unboxed as VU
import qualified Data.Vector.Unboxed.Mutable as VUM

emptyTable :: Int -> Int -> V.Vector (VU.Vector Int)
emptyTable m n = V.replicate n $ VU.replicate m 0

incrementTable :: V.Vector (VU.Vector Int) -> Int -> Int -> V.Vector (VU.Vector Int)
incrementTable t i j = runST $ do
  mTable <- V.thaw t
  VM.modify mTable (\v -> runST $ do
    mV <- VU.unsafeThaw v
    VUM.modify mV (+1) i
    VU.unsafeFreeze mV)
    j
  V.freeze mTable

main = do
  let t = incrementTable (emptyTable 2 2) 1 1
  replicateM_ 5 $ print t
```

It builds a 2x2 table and increments the lower right corner. In theory, it should print 5 lines of `[0,0],[0,1]` however it does not do so in all cases:

```
 λ stack clean && stack build --fast && stack exec test
test-0.1.0.0: configure (exe)
Configuring test-0.1.0.0...
test-0.1.0.0: build (exe)
Preprocessing executable 'test' for test-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/test/test-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/test/test ...
test-0.1.0.0: copy/register
Installing executable(s) in
/tmp/test/test-2/.stack-work/install/x86_64-linux/lts-8.12/8.0.2/bin
[[0,0],[0,1]]
[[0,1],[0,1]]
[[0,1],[0,1]]
[[0,1],[0,1]]
[[0,1],[0,1]]
```

Observe how the last 4 lines are the wrong `[[0,1],[0,1]]`. More calls to `incrementTable` produce even wronger numbers.

So far, this seems to happen when building with `--fast` or when the cabal file sets the `-O0` flag.

It might be related to #139 but that only mentions documentation changes. Might also be an upstream bug (the trac ticket linked in #139: https://ghc.haskell.org/trac/ghc/ticket/12656)

Removing the unsafe operations makes the code behave properly in all cases. However, my original use case requires `unsafeThaw` and `unsafeFreeze` on both coordinates due to the `incrementTable` being called in a tight loop.

The workaround that I use now (with a small hit in performance) is

```haskell
incrementTable :: V.Vector (VU.Vector Int) -> Int -> Int -> V.Vector (VU.Vector Int)
incrementTable t i j = V.modify (\v -> VM.modify v incFun j) t
  where
    incFun = VU.modify (\v -> VUM.modify v (+1) i)
```

**Comment by RyanGlScott** [comment]
FWIW, I can't reproduce this bug in GHC 8.2.1:

```
$ /opt/ghc/8.2.1/bin/ghc -O0 Bug.hs -fforce-recomp
[1 of 1] Compiling Main             ( Bug.hs, Bug.o )
Linking Bug ...
rgscott@gearloose:~/Documents/Hacking/Haskell$ ./Bug
[[0,0],[0,1]]
[[0,0],[0,1]]
[[0,0],[0,1]]
[[0,0],[0,1]]
[[0,0],[0,1]]
```

I'm not sure which commit fixed it off the top of my head, however.

**Comment by mihaimaruseac** [comment]
That's good to hear. I'll investigate soon if that fixes my issues too.

**Comment by cartazio** [comment]
What happens if you mark the incrementable function noInline?


Either way, inplace freezing and thawing a pure thing and not being the
source of the function is very dangerous.  I would suggest not doing it
this way.  It will eat your pants

**Comment by mihaimaruseac** [comment]
Marking `incrementTable` no inline has no effect.

**Comment by dolio** [comment]
The output you are seeing looks expected to me. Ryan's output looks unexpected.

`emptyTable 2 2 = V.replicate 2 $ VU.replicate 2 0`

This is a boxed array of unboxed arrays of 0s. The unboxed array is shared, so the boxed array has two pointers to the same (in memory) array.

`incrementTable` thaws the boxed array, but this just makes a new boxed mutable array containing references to the same unboxed array. Then it uses `unsafeThaw` to make that single unboxed array mutable temporarily, and modify its contents. Since there's only one unboxed array in play, you get the output you see. The reason why you see `[0,0]` at the start is that the modifying hasn't happened yet.

I'm not sure how to explain Ryan's results. I guess something is breaking the sharing on GHC 8.2. But the moral is: this is (one reason) why `unsafeThaw` is unsafe.

**Comment by mihaimaruseac** [comment]
But with optimizations the unboxed array is no longer shared, since the output works as expected.

Also, intuitively, it should not share the same array but create a new unboxed array. Isn't the purpose of `replicate n` to create `n` copies of the same thing?

**Comment by dolio** [comment]
It's impossible, generally, for `replicate n` to even accomplish the job of creating `n` different (in memory) copies of its argument, because it is polymorphic, and there is no Haskell primitive for creating a separate-in-memory clone of a value of an arbitrary type. The reason it happens with optimizations is probably inlining of things to the point where the initial unboxed array expression is no longer shared in the code.

And the only reason these optimizations are done is on the presumption that transformations from `let x = VU.replicate 2 0 in (x, x)` to `(VU.replicate 2 0, VU.replicate 2 0)` and the like are valid. Your use of `unsafeThaw` breaks this presumption. But that is on you; it is an unsafe function.

I don't know whether it's intuitive or not. But the straight forward lazy evaluation reading of the original code would lead to expecting the results you got. A call-by-value reading would lead to expecting all `[0,1]`. Only call-by-name (where arguments are re-evaluated as many times as they're used) would lead to your desired output.

**Comment by mihaimaruseac** [comment]
I understand what you're saying but it still doesn't click. The workaround solution would not work either if what you say is true, I think.

**Comment by dolio** [comment]
`VU.modify` makes a new array, just like using `thaw` instead of `unsafeThaw` would.

**Comment by mihaimaruseacleapyear** [comment]
Did some more testing and I'm now leaning on @dolio's point of view. But now I'm worried that 8.2.1 will change this to actually do what I was wrongly expecting, as Ryan says.

**Comment by cartazio** [comment]
either way, while we're happy to help you understand this better, there is no bug, unsafe in this context has to do with *impurity* and *in place update*, rather than bounds checking.

(happy to reopen it if @RyanGlScott  or @dolio  think otherwise, but at the end GHC will do interesting optimizations to code that claims is pure :) )
