### ISSUE TITLE
How do I generate an IO Vector?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/vector#175]
[`Data.Vector` has `generate :: Int -> (Int -> a) -> Vector a`](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector.html#g:7) but I don't see an equivalent in `Data.Vector.Mutable`.  What am I missing?

**Comment by cartazio** [comment]
Make a new vector and iterate :)

The mutable API is kinda poor for historical reasons but we have plans to
improve it time / contributions permitting :)

**Comment by tomjaguarpaw** [comment]
So if someone submitted a PR to add `generate` it would likely be accepted?

**Comment by dolio** [comment]
I think the API for mutable vectors is lacking a lot of utilities, so yeah, I'd accept it.

It may be that there's a rewrite rule in place to turn any `Vector` construction into a corresponding `MVector` construction (because if you think about it, building an immutable vector has to be building a mutable vector and then freezing). However, off hand I don't know what it is, and it isn't the most obvious thing to try. I could take a look if you'd be interested in that, though.

**Comment by Shimuuar** [comment]
Closed in favor of #334
