### ISSUE TITLE
reenable tests in travis CI

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#199]
Hey @RyanGlScott I noticed that we're flat out disabbling the test suite instead of only doing the O0 variant, was the build OOM/timing out on O0 or O2?

if thats the case, lets fix the underlying issue, whether its one or the other :) 

If possible, I'd like to also get the O2 one's back live, because its a pretty good stress test of current GHC over time on a widely used library that depends heavily on O2 features (or we should figure out what subset of O2 we can enable to strike a balance)

**Comment by RyanGlScott** [comment]
I've re-enabled just the `-O0` tests for problematic GHCs in 61fe37f8359dcad065fc55dee43a414ad4382f1b.

I don't recall what the issue was preventing GHC 7.10 from running the `-O2` tests, but GHC 8.2 and later cannot run them due to https://ghc.haskell.org/trac/ghc/ticket/13535, which is firmly a GHC bug.

**Comment by RyanGlScott** [comment]
Well, shoot. I thought I carefully excluded the `vector-tests-O2` target from the problematic GHC configurations, but as [this Travis build](https://travis-ci.org/haskell/vector/builds/331606324) shows, it's still bringing in `vector-tests-O2` every time ([here](https://travis-ci.org/haskell/vector/jobs/331606328#L864), for example). I have no idea why `cabal new-build` is doing that... @hvr, any ideas?

**Comment by Shimuuar** [comment]
I believe this problem is fixed in #273
