### ISSUE TITLE
 Document semantics of take, drop, and grow for mutable vectors

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#206]
On a mutable vector, take and drop alias the vector.  This is not documented.  Additionally, it is unclear whether or not the API supports using the original vector after calling take or drop. What about grow?  The way things are implemented now, it seems safe to reuse the original vector. There is no aliasing.  But is this a guarantee that the API makes?  This should also be documented.

**Comment by cartazio** [comment]
This depends on the instance too right?

I’m not sure what semantics we can give to grow , since that’s def instance
dependent.  All current implementations are currently like an allocation
and memcopy.  There are other approaches, but I’m not sure what strategies
are viable for ghc.  @bgamari might know.

Take and drop are always generic over the instance , so probably aliasing.

How the semantics reconciles with stream fusion is probably an important
detail.

I could be wrong though.

**Comment by andrewthad** [comment]
Currently, there's no way to implement grow that causes aliasing to happen. The primop `resizeMutableByteArray#` only aliases if you shrink the buffer and always copies if you grow it. So, right now, it's always safe to reuse the vector. If someone eventually implements in-place growing of mutable byte arrays, there may come a day when its not (for primitive vectors and unboxed vectors). I think it may be prudent to preemptively say something like "the vector passed into this function shall not be reused". All internal uses of grow already satisfy this requirement.

Also, we could already make grow do aliasing in some cases. What if the someone called take on a mutable array and then wanted to grow it later. There's still space left after the vector. We could simply adjust the length to reclaim the space. This would work for all types of vectors.

Since `take` and `drop` always do aliasing, we should document that. We should probably also discourage use of the original vector, since that way lies madness.

> How the semantics reconciles with stream fusion is probably an important detail.

To my understanding, mutable vectors don't support stream fusion.
