### ISSUE TITLE
Timeline for hackage push?

### ISSUE THREAD

**Issue by mstksg** [haskell/vector#211]
Thanks for the great package!  Just wondering if there was anything in particular holding up a hackage push of the changes from the past year or so, or if there was a timeline for things that needed to be prepared first.  I have some packages that I have been delaying release of pending a hackage push of 3c51c33, so it'd be useful to get a rough estimate! :)

Thanks again!

**Comment by taktoa** [comment]
It's frankly terrifying to me that a basic function like `maximumBy` has been broken in the stable release of `vector` for almost two years, despite the fact that the bug [was fixed](https://github.com/haskell/vector/commit/2ae8a575466e862fb63192d7504f6a9389cae729) quite some time ago.

**Comment by glguy** [comment]
It'll be good to get a new version, but it's not particularly terrifying. It isn't even documented behavior that you'd get either one or the other result. Relying on the difference this commit makes would be a mistake even after release.

**Comment by cartazio** [comment]
indeed, its outside of the basic specified behavior, so its merely about "substituteability of basic data structures"

likewise, for core libraries like vector, its better to be slow moving than fast. maturity and stability are their value prop (though better ideas and improvements are always good, they need to justify themselves)

**Comment by cartazio** [comment]
i need to decide what stuff in master is solid enough for the next release, and what needs more baking. then i'll take part of a day to make sure its all good, then do a release.

**Comment by basile-henry** [comment]
@taktoa As the others said I wouldn't rely on a specific behaviour one way or another for `maximumBy` and friends with respect to the `EQ` case. The rationale behind that commit was just to get it consistent with the list version, not that one implementation was correct and the other wasn't. Since lists are part of `base` it seemed simpler to change the `vector` implementation. :smile: 

<hr>

Slightly *off-topic* but this might still be of interest as another example of an arbitrary decisions for the `EQ` case in `base`:

```haskell
λ > max 0.0 (-0.0)
-0.0
λ > max (-0.0) 0.0
0.0
λ > 0.0 == (-0.0)
True
```

**Comment by chessai** [comment]
this is done.

**Comment by cartazio** [comment]
Thx ;)
Lots track of these dangling things
