### ISSUE TITLE
Document that uniq keeps the last duplicate

### ISSUE THREAD

**Issue by rightfold** [haskell/vector#214]
The documentation of _uniq_ does not specify exactly which elements are kept.

```haskell
-- assume a /= b, b == c
Vector.uniq [a, b, c] = [a, c]
```

This is important when _Eq_ instances do not consider all parts of the data structure.

Do you think this should be documented (and tested), or should this be left unstable?

**Comment by andrewthad** [comment]
If it is unstable, this should at least be documented.

**Comment by glguy** [comment]
I'd prefer things like this be documented to be unstable so that people aren't expected to memorize which behavior functions like these have when they're reading code using them. Instead of supporting the use of a surprise `Eq` instance via functions like `uniq` functions that were explicit about their behavior and were parameterized over a relation that didn't have the implicit baggage of `Eq` would be much more appropriate.
