### ISSUE TITLE
Are cons and snoc really O(n) operations?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [haskell/vector#237]
That's what [the documentation on Hackage](http://hackage.haskell.org/package/vector-0.12.0.2/docs/Data-Vector.html#v:cons) says. I would have expected them to be O(1).

**Comment by chessai** [comment]
Edited your link to point to `cons` instead of the section on `Folds`.

**Comment by cartazio** [comment]
yes, it has to.  vectors are flat,  prepending/appending a single element requires a vector with 1 additional slot! Theres perhaps alternative design approaches which would do a memmove/reallocation, but thats kinda not something in vector as its designed.

uncons/unsnoc can be O(1), via slicing.

if you know of an O(1) worst case approach that works for flat sequence in virtual memory structures rather than nested pointer/references, please do share.

**Comment by JeffreyBenjaminBrown** [comment]
Ah, yes, of course, you're right. Thanks!
