### ISSUE TITLE
SIMD support in the vector library

### ISSUE THREAD

**Issue by Magalame** [haskell/vector#251]
Hi!

I was wondering if there were any plan to add support for SIMD instructions to `vector` now that [GHC supports them even without llvm](https://gitlab.haskell.org/ghc/ghc/commit/acd795583625401c5554f8e04ec7efca18814011)?

Thanks to @drezil and @klapaucius I'm aware of [this paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/haskell-beats-C.pdf) and [this work](https://github.com/mainland/vector/commits/simd), but the branch is 6 years old and so probably doesn't reflect the current direction of `vector`. 

If there's any need for help, I'd be more than happy to contribute!

**Comment by Magalame** [comment]
Came from https://github.com/lehins/massiv/issues/80

**Comment by chessai** [comment]
as far as i am aware, that commit you link to doesn't actually work as intended. @bgamari and @AndreasPK would be able to say why, if so.

**Comment by andrewthad** [comment]
Here's the commit that reverted NCG SIMD support: https://gitlab.haskell.org/ghc/ghc/commit/db948daea6c01c073f8d09a79fa5adda279fbf0c

**Comment by Magalame** [comment]
Thanks @andrewthad for the link! Do we know when it'll be added back?

**Comment by chessai** [comment]
@Magalame i know the two individuals that plan on implementing it/supervising its implementation are Ben Gamari and Andreas Klebinger.

**Comment by bgamari** [comment]
@AndreasPK has indeed expressed interest in picking it up. In short, the commit as written has an overly-simplistic view of register allocation and breaks in some cases.

**Comment by cartazio** [comment]
More broadly : the way fusion based optimization as realize in vector vs
the way simd performance engineering work mean they will seldom happen
together.

Broadly : even once ghc has better simd support, the only way to get robust
performance out of it will be via hand coded routines.  The way vector
fusion works means any auto simd inclusion in vector  will not actually be
a compelling case for simd ...

I’m open to being wrong, but the optimization architecture of vector and
the patterns for General simd performance are very different.  Plus there’s
some very precise constraints on when simd supports what datatypes.


I will say this: maintaining a hypothetical future simd vector as a quality
default would require orders of magnitude more contributors being
comfortable improving and contributing to the internals of vector design /
fusion architecture etc wise.  Barring  that , even when ghc gets good
simd, there won’t be enough contributor bandwidth to maintain that massive
portability and performance liability.

I’m oversimplifying this massively  but I do agree it’s be an interesting
direction. Just one that’s actually incredibly subtle and challenging to do
well.  Let alone maintain one support!

**Comment by Magalame** [comment]
@bgamari @AndreasPK  thanks a lot for the work you're putting into this. Do you have a general idea of when it would be available?

**Comment by Magalame** [comment]
Thanks @cartazio for the details, I thought the `MultisC` type would have ensured a relatively seamless integration?

**Comment by cartazio** [comment]
it worked as a technology demonstrator, but simd as it currently exists in the forseeable future is incredible monomorphic, only really for vectors on Float/Double/Int32/Int64/Word32/Word64, so it would only pay off for a pretty spare/small fraction of user code. 

It is possible that a future version of vector could allow simd integration to the fusion framework, but given engineering priorities for the future of vector as they currently exist, unless we can jointly improve the current O2 compilation performance AND fusion quality first, its not going to happen ever.  Adding another rewrite rule layer to the current setup seems like piling architecture debt. 

that aside, not enough compiler support in the GHC layer actually exists to robustly support simd across all supported targets. And since vector is so widely used, that might be a blocker to including it in core vector as a library until conditional compilation / distinct code paths per microarchtecture is sanely supported at the GHC layer.

if you want to experiment rebasing the multiC change set onto vector master or friends, so we can look at it in an up to date way, i'm all ears. We just genuinely dont have the time/resources/bandwidth though. And i'm skeptical that its the right architecture going forward

**Comment by Magalame** [comment]
I see, thanks so much for taking the time to answer!

**Comment by cartazio** [comment]
I appreciate your interest!  It’s just a tricky area and evaluating user
benefit / impact is super challenging.

**Comment by GeorgeCo** [comment]
I assume that if you compile with llvm you will get SIMD instructions when applicable. Is that false?

**Comment by cartazio** [comment]
If you disable fusion and write imperative code that can be loopified, simd
might happen.  But streams are kinda at odds at least the simpler loads and
stores that I think some autovectorization can see easily.  But I haven’t
tried out stuff with ghc and modern llvm so I could be wrong.

**Comment by Drezil** [comment]
Depends on the operations you do.
vector is basically an implementation of the "recycle your arrays"-paper. It has streaming-capabilities AND block/buffer ones. What gets done is ruled by compiler optimisations and if the generated llvm looks code looks optimizable for libllvm than those things get turned into simd operations. But it is hit and miss - as far as I remember.
It has been years when I last looked into it .. so it may have changed in the meantime.

**Comment by cartazio** [comment]
I’ve not seen that paper before, is there a good link?

But yeah, you’re absolutely right that it will sometimes fire. But also
that unless you’re mentally modelling the generated core that’s passed to
llvm you’re not gonna have anything reliable with the current stuff
