### ISSUE TITLE
This repo is at 0.12.0.1, while hackage has 0.12.0.3

### ISSUE THREAD

**Issue by AndreasPK** [haskell/vector#255]
Is there a newer mirror? Was the hackage version manually bumped?

This is quite odd.

**Comment by llelf** [comment]
It’s probably from [there](https://github.com/haskell/vector/blob/v0.12/vector.cabal).

**Comment by cartazio** [comment]
Good catch.  I should sync it over :).
Thx!

**Comment by cartazio** [comment]
https://github.com/haskell/vector/blob/19189a884434ecd2c96212395f5705347b55775b/vector.cabal 
its def here locally in the v0.12 branch https://github.com/haskell/vector/tree/v0.12

**Comment by cartazio** [comment]
@lehins https://github.com/haskell/vector/blob/v0.12.0.3/vector.cabal should be the correct tag, can you confirm?

**Comment by cartazio** [comment]
@AndreasPK should build fine now :)

**Comment by lehins** [comment]
>  can you confirm?

@cartazio Yeah, it looks good. There was a revision [`r2`](https://hackage.haskell.org/package/vector-0.12.0.3/revisions/) since the tag, but I I don't think it's important to update tags with new revisions. Now looking back at this ticket I guess the confusion in this ticket was that the master branch was behind the actual release.
