### ISSUE TITLE
Building test suite takes way too much memory 

### ISSUE THREAD

**Issue by Shimuuar** [haskell/vector#272]
Building tests take a long time which is quite annoying for developing. But what even worse it uses a _lot_ of memory: 17GB with GHC8.6 & 14GB with GHC8.4. That's clearly a problem for anyone trying to work on vector on laptop. 

I don't know how bring memory consumption down. Maybe split Tests.Vector?

**Comment by cartazio** [comment]
agreed! i've never gotten it to build on recent ghc  with a < 16gb ram laptop
hrm, if splitting it into 5-10 smaller things decreases blow up, i'm all for it! 

that said, what i would dearly love is to figure out how to check https://gitlab.haskell.org/ghc/ghc/merge_requests/611 the zap coercions work would fix our stuff

**Comment by cartazio** [comment]
also that would drmatically remedy the lack of CI coverage that bit us

**Comment by cartazio** [comment]
ok, weirdly enough the old vector test suite was split into per function test files ... maybe we should go back to that ?!

**Comment by cartazio** [comment]
at least in the 0.12 branch theres still the old test suite, where everything is split into tiny little modules... can youg et that running humanely? i'm trying a different idea quickly atm

**Comment by lehins** [comment]
I've seen this sort of blow up before. If I had to guess, it is due to a lot of inlining, but I could be wrong of course. I am pretty sure splitting into modules would alleviate the problem. It would be an improvement regardless of this issue, since separating properties into logical would make the test suite a bit easier to navigate.

**Comment by cartazio** [comment]
i'm doing the dumb epxeriment of rubbing the magic noinline combinator over every property but i'm not sure if thats helping, though peak memory usage so far is ~4.23 gb, which i think is a genuine improvement.... assuming we can still get the same bugs tickled and the build time isn't inhumane.  I suspect youre right though that the **best** mitigation might be a kajillion little test suites, especially 

my rubbing NOINLINES EVERYWHERE works, build din't go past 4.7 gb of ram , and the reported time via the cli `time` tool was 
 293.36 user

      304.40 real       293.36 user         5.21 sys

**Comment by cartazio** [comment]
i'll push a branch so we can poke at it and discuss! the fromEnumTo  tests even failed :)

**Comment by cartazio** [comment]
amusingly or amazingly, the mac system call sampler actually showed a lot of ghc passes in the stack trace sampler

**Comment by cartazio** [comment]
[Sample of ghc vect test 02 sampel 1.txt](https://github.com/haskell/vector/files/4130652/Sample.of.ghc.vect.test.02.sampel.1.txt)

we should probably share this with ghc folks

**Comment by lehins** [comment]
Doing noinline on tests is a bad idea to solve this problem, cause we want those functions that are being in test cases to do all of the possible inlining, since that is bread and butter of vector optimizations, which we definitely want to test.

While we are on the subject of a test suite, have you guys thought about using `hspec`? It produces a way nicer output and doesn't rely on template haskell to combine all of the unit tests and quickcheck properties. Not saying that we should start switching right away, I just thought I'd throw it out there, since it took me a lot of scrolling to find the failing test cases.

**Comment by cartazio** [comment]
the noinline in question i'm doing is on QC outside. I do agree we need to make sure rules dont have bugs / are correct. 

I have at least a demonstrator where memory usage seems to peak at 4.7gb total and finish 
 281.60 real       273.21 user         5.06 sys AND  catches bugs

**Comment by cartazio** [comment]
i'd actually perfer tasty over hspec because the deps are more parsimonious. but changing the test suite design shouldn't be the focus (theres enough near term stuff we should catchup)

**Comment by cartazio** [comment]
see the branch `wip/carter/vector-noninline-testsuite02` on the `haskell/vector` repo for the commit 19189a884434ecd2c96212395f5705347b55775b which makes the build time and memory humane on portable laptops.

**Comment by lehins** [comment]
@cartazio That's fine, I just thought I'd ask. QuickCheck and HUnit is the main power anyways.
> perfer tasty over hspec ...
> changing the test suite design shouldn't be the focus

The branch and commit only relax bounds, I don't see how that alone can reduce build time. Are you sure you pushed to remote?
> see the branch wip/carter/vector-noninline-testsuite02 on the haskell/vector repo for the commit 19189a8 which makes the build time and memory humane on portable laptops.

**Comment by cartazio** [comment]
WOOPS, check agin :)

**Comment by cartazio** [comment]
i pushed two commits now

**Comment by cartazio** [comment]
first one, rubs noinline everywhere, and actually seems to spend more time on optimization function calls if i'm reading OSX system tracing stats correctly, the second one i only do noinline on the test property groups and the memory usage goes up from 4.7 to 6.7 gb

either way, seems to have largely equivalent timeings eg `   294.94 real       277.48 user         6.47 sys`

**Comment by lehins** [comment]
I personally would recommend to split `Test.Vector` into submodules, rather than adding `noinline` anywhere in the test suite, because it messes with the code we are trying to test, it prevents a lot of other inlining from happenning (which is why it reduces the memory usage).

If you don't like the argument above, think about the user that will be writing the same code as in the test suite. Will he be placing the `noinline` next to the function he is trying to use? Very unlikely! Which means we will not be testing the same usage pattern as most users will happen to be using.

**Comment by cartazio** [comment]
ok, 
1) this use of noinline will not prevent the arguments subexpressions of noinline from simplifying and rewrite rules from firing.  (the thing we actually )

2) the semantics wrt optimization OF the noinline magic function is the same as
```
{-# NOINLINE noinline #-} 
noinline :: a -> a 
noinline x  = x 
```
except that after the optimizer runs, it reases that extra id function application away to  remove an indirection

3) I do agree this is a BAD FIX from a contributor and maintainership long term view. 

what are ways we can fix it?

a) have a set of Unit test and quickcheck helpers that  just NOINLINE  pragma up those functions and only allow those to be imported in?

b) let a thousand little smaller test modules bloom! :) 

i'm open to both directions honestly, but priority zero is having a working full CI build matrix we can all trust, so i'd rather that fixup be AFTER we get the release out the door :0

**Comment by cartazio** [comment]
to be clear @lehins you're absolutely correct, i just dont want to have that bottleneck being able to make some other progress.  and either way, the real issue is fixing the underlying changes to ghc that force this. I believe coercions machinery is part of that, and these blowups need to be more user debuggable

**Comment by lehins** [comment]
1. It doesn't really need to be a thousand modules. Splitting into 5 submodules should reduce the memory consumption more than adding those noinlines.
2. 6.7Gb is already dangerously close to 7.5Gb limit on travis. 

I think it's better to fix correctly right of the bet. I am gonna give it a shot right now see what I get. I'll let you know as soon as I have some results

**Comment by cartazio** [comment]
yes, the all noinlines one is 4.7gb, which would work for now and buy us some time :)

**Comment by cartazio** [comment]
ok, i think i have a way we could make the no inline stuff mroe humane

**Comment by cartazio** [comment]
@lehins if you find the time to whip up a demonstrator on master, that'd be fantastic :) 

i'm open to changing what runner toolkit we use if its a clear win and easy to demonstrate the win.

**Comment by cartazio** [comment]
atm i'm just seeing if i can get the full build matrix on travis CI with this change set (grotty as it currently is, because that'd be a huge improvmeent :) )

**Comment by cartazio** [comment]
either way, thanks !

**Comment by lehins** [comment]
TADA!!!

We can catch the `enumFromTo`  #268 bug on the CI: https://travis-ci.org/haskell/vector/jobs/643634651#L3309

**Comment by cartazio** [comment]
BRAVO. i'm gonna confirm locally of course  + do a secondary tweek to get things green wrt updating the travis scripts
