### ISSUE TITLE
Data.Vector.Fusion.Stream.Monadic contains a lot of dead code

### ISSUE THREAD

**Issue by Shimuuar** [haskell/vector#275]
I noticed that when I was fixing enumFromTo bug. I think we should do something about it. Probably we should just delete it since it's easiest option in terms of maintenance. It would require major bump according to PVP

**Comment by lehins** [comment]
Which code in  particular you were thinking of? If it is something that is really dead and not exported then hell yeah, why not. Be we gotta keep in mind that some of the exported functions might be used by other libraries, even if they are not being used by other vector modules.

For example I use quite a few functions from `Data.Vector.Fusion.Stream.Monadic` in massiv. I think this streaming functionality hella' useful, enough so that it could be its own library!

**Comment by Shimuuar** [comment]
Dead as "exported but not used anywhere". Problem is it _will_ bitrot. I
could've forgotten to fix enumFromTo in Stream module and no one would
notice.

There's overlap between Bundle and Stream. All in all I think choice is
between removing or adding tests

>

**Comment by Shimuuar** [comment]
Now that we decided to split stream into separate package this issue could be safely closed
