### ISSUE TITLE
`new` (mutable unboxed vector) hands the user uninitialized memory

### ISSUE THREAD

**Issue by rwbarton** [haskell/vector#30]
I don't think it should be the default behavior in a managed language to provide access to uninitialized memory. Aside from potential security issues, it also means that computations using mutable unboxed vectors in ST are nondeterministic. At the very least, this behavior should be clearly documented!

Naturally some applications need uninitialized arrays. I would suggest repurposing the name `unsafeNew` for this (the current `unsafeNew` is silly—I can't imagine any application for skipping the bounds check of an allocation), or using a new name like `newUninitialized`.

The same comments apply to `grow` and `unsafeGrow`.

For comparison, the array package has a `newArray` with an extra argument which is used as the initial value of every entry of the new mutable array, and a `newArray_` which (for unboxed arrays) produces an uninitialized array when used in `IO`, and an array initialized to a fixed value (depending on the type) when used in `ST`.

**Comment by treeowl** [comment]
I have a fairly strong preference for maintaining a "trust me" option (to maintain the "performance at any cost" theme of this package). Repurposing the `unsafe` names for this sounds good to me personally, but `uninitialized` sounds fine too.

**Comment by dolio** [comment]
The problem, last I checked, is that fixing this while leaving an escape hatch requires adding operations to be very good. You need a generic `initialize` function that will do things for unboxed vectors and not for boxed vectors (because they are already initialized). It's rather more nice to fix by making even `unsafeNew` initialize the memory.

I also question whether array allocation is ever a bottleneck that requires "performance at any cost." And we need something like that to justify the more complicated solution.

**Comment by treeowl** [comment]
I imagine it could be significant in an array-doubling situation like an unfold.

**Comment by dolio** [comment]
This has been fixed. Released in 0.11.0.0.
