### ISSUE TITLE
set up CI for primitive HEAD

### ISSUE THREAD

**Issue by chessai** [haskell/vector#318]
There are a lot of changes coming to the primitive library soon. It would be nice to have CI track it, so that those changes are not causing any breakage. 

cc @andrewthad

**Comment by Shimuuar** [comment]
What is the goal? If it's to ensure that released vector does not break with new primitive then it's better to build vector as part of primitive's CI. 

Somewhat tangentially. I would be nice to test that vector builds with primitive releases it claims to be compatible. Cabal usually just picks latest release

**Comment by lehins** [comment]
@chessai I was following the changes to primitive package closely and I didn't see anything that could affect vector in a negative or breaking way. I also just ran the test suite against `primitive` master with no problems. At the same time, because `primitive` and `vector` are so tightly coupled I do fancy the idea of having a single build in a CI matrix for both packages that builds against each other's master branches. This way we can prevent unexpected breakage ahead of time.

**Comment by chessai** [comment]
Yeah, I don't think any changes to primitive to-date will cause breakage. But having some kind of special CI for these two would be great, testing vector against specific versions of primitive. (Side note: Really anything older than primitive 0.6.4.0 should be deprecated because of the insane amount of bugs/quirky behaviour in a lot of the old broken instances defined there, it would suck for users to see random bugs due to this, but I think this is not yet feasible because it is a boot package).

**Comment by lehins** [comment]
@chessai, by "boot" you mean wired with ghc? If so `primitive` isn't a boot package. Regardless of this it is still possible to use different versions of boot packages than what comes with ghc. For example I can use `bytestring-0.10.8.2` with my packages and compile them with any modern ghc, such ghc-8.8.2 for example. One thing I can't do is use `bytestring-0.10.9.0` with any ghc other than ghc-8.8.1`, because it is still not up on hackage :)

**Comment by Shimuuar** [comment]
Is this still relevant? I guess it could be closed.

**Comment by Shimuuar** [comment]
Issue seems to be obsolete. I'm closing it. Please yell if you disagree
