### ISSUE TITLE
Switch benchmarks from criterion to gauge

### ISSUE THREAD

**Issue by Bodigrim** [haskell/vector#321]
At the moment benchmarks are pretty much useless, because `criterion` depends on `vector` not only directly, but also transitively on many occasions. 
```
In the dependencies for aeson-1.4.7.1:
    vector-0.13.0.1 from stack configuration does not match >=0.12.0.1 && <0.13  (latest matching
                    version is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> aeson-1.4.7.1

In the dependencies for cassava-0.5.2.0(-bytestring--lt-0_10_4):
    vector-0.13.0.1 from stack configuration does not match >=0.8 && <0.13  (latest matching version
                    is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> cassava-0.5.2.0

In the dependencies for microstache-1.0.1.1:
    vector-0.13.0.1 from stack configuration does not match >=0.11 && <0.13  (latest matching version
                    is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> microstache-1.0.1.1

In the dependencies for vector-algorithms-0.8.0.3:
    vector-0.13.0.1 from stack configuration does not match >=0.6 && <0.13  (latest matching version
                    is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> vector-algorithms-0.8.0.3

In the dependencies for vector-binary-instances-0.2.5.1:
    vector-0.13.0.1 from stack configuration does not match >=0.6 && <0.13  (latest matching version
                    is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> vector-binary-instances-0.2.5.1

In the dependencies for vector-th-unbox-0.2.1.7:
    vector-0.13.0.1 from stack configuration does not match >=0.7.1 && <0.13  (latest matching
                    version is 0.12.1.2)
needed due to vector-benchmarks-0.10.10 -> vector-th-unbox-0.2.1.7
```
I suggest we switch from `criterion` to `gauge` to simplify this sort of things.

----

(In the long term one could probably patch `gauge` to use `primitive` instead of `vector`)

**Comment by Shimuuar** [comment]
+1. I though about this myself.

**Comment by lehins** [comment]
Not a big fan of `gauge`, but dependency graph does make it look more appealing than criterion.

**Comment by Bodigrim** [comment]
It appears that `vector` benchmarks allow to specify `seed` and `size` as additional command line arguments to overrride defaults (`seed = 42`, `size = 2000000`). It is cumbersome to add additional command line arguments in `gauge`. 

I personally am happy to sacrifice these options: do not see much point in changing `seed` from default. With regards to `size`, in my projects I tend to create a bunch of benchmarks for growing sizes beforehand and switch between them using filters. Anyways, I suspect that no one used this stuff for a long time. @lehins @Shimuuar what is your opinion?

**Comment by AndreasPK** [comment]
> At the moment benchmarks are pretty much useless, because criterion depends on vector not only directly, but also transitively on many occasions.

This makes them annoying to benchmark but by far not useless! After all there are workarounds but they are not convenient.

> Anyways, I suspect that no one used this stuff for a long time. 

I only added the flags about two years ago and used them about a year ago again.

It has been a while, but it's not all that far back.

> I personally am happy to sacrifice these options: do not see much point in changing `seed` from default.

Since I added them I'm obviously biased. The reason why I added them is a bit tricky:

Vector benchmarks in regards to *runtime* are hard to measure well. The performance of the current set of benchmarks depends both on the input size *and* the actual values (determined by the seed).

But performance is *also* dependent on problem sizes (cache effects and whatnot).

For this reason to get a reliable benchmark one needs to measure:
* Different seeds
* At different problem sizes

As the problem size grows the importance of the seed dwindles. But not all kinds of changes can be characterized by running large problem sizes. However many can which is why I made this the default.

> With regards to size, in my projects I tend to create a bunch of benchmarks for growing sizes beforehand and switch between them using filters.

One could create a matrix of different seeds at different sizes. But if you make this large enough to cover most cases running all benchmarks will take so lang that many people might not bother.

------------------------------------

In the end however I can see how most people won't care about these flags. And changing the seed, while important for some cases, is rather niche. So removing them is fine by me (for what it's worth).

But it would be good to preserve the option to easily change the seed in the code at least.

**Comment by Bodigrim** [comment]
I think it is important to keep benchmarks as easy to use as possible. 

If a certain function exhibits different behaviours for growing problem sizes, let's add separate benchmarks for representative sizes. I do it all the time for my packages. If a certain function exhibits different behaviour depending on a seed, let's include benchmarks for several different seeds. If benchmarks happen to take too long, a contributor can simply filter out irrelevant ones, which is much easier than inventing a set of undocumented parameters each time anew.

Sure, I'll retain an option to change size and seed in source code.

**Comment by lehins** [comment]
@Bodigrim I agree with all you say,

> If benchmarks happen to take too long, a contributor can simply filter out irrelevant ones

That's the killer feature in criterion that I really like `--match [prefix|patter] ...`, which as far as I know is missing from gauge.

**Comment by Bodigrim** [comment]
@lehins `gauge` features the same command-line option:
```
  -m MATCH  --match=MATCH       Benchmark match style: prefix (default), exact, pattern (substring), or ipattern (case insensitive)
```

**Comment by lehins** [comment]
@Bodigrim You are right. I was sure it doesn't work, but I just tried it and it works. I wonder why I it didn't work for me before. Oh well, good to know. Thank you ;)

**Comment by lehins** [comment]
@Bodigrim Oh damn, I remember now, it is the `--output` command that doesn't work and is silently ignored.
