### ISSUE TITLE
Add upsert function

### ISSUE THREAD

**Issue by flip111** [haskell/vector#342]
Could an upsert function be added? Named after https://wiki.postgresql.org/wiki/UPSERT it would look something like

```haskell
upsert :: (a -> Bool) -> (a -> a) -> a -> V.Vector a -> V.Vector a
upsert f g elem vec = case V.findIndex f vec of
  Nothing -> V.snoc vec elem
  Just index -> let old_elem = vec V.! index
                    new_elem = g old_elem
                in V.modify (\v -> V.write v index new_elem) vec
```

I'm not sure if this is the most efficient implementation or if the argument order is the best. Also maybe it's better to create two variants instead: one for snoc and one for cons.

**Comment by Bodigrim** [comment]
IMHO this looks too specific for inclusion.

**Comment by Bodigrim** [comment]
This pattern does not seem to be in a high demand (because no one has asked for it in so many years), and is easy to implement in a client library (with snoc/cons, another order of arguments, removing other elements satisfying the predicate, over mutable vectors, whatever). Also this routine does not seem to benefit from fusion. 

Adding new functions to `vector` API is costly, because you need to implement them for all vector flavours and support, basically, forever.

**Comment by lehins** [comment]
I am also not in favor of adding such function to vector for same reasons that @Bodigrim already pointed out and because it is an O(n) operation that requires a copy of the whole vector just to upsert a single element. Something like an IntMap would be a better data structure for such operation IMHO.

That being said, I think it would be possible to create an implementation that could utilize stream fusion. It would look very similar to `findIndex`. However I am not sure it is really worth the effort because even such implementation will probably not going to have great performance characteristics.

I thought for a second about closing this ticket but maybe we should keep it open for a while and let others chime in. Who knows maybe someone will decide to create an implementation together with a benchmark comparing performance to alternative data structures.

**Comment by flip111** [comment]
Is also somewhat similar to this function https://hackage.haskell.org/package/unordered-containers-0.2.13.0/docs/Data-HashMap-Strict.html#v:alter

differences:
```haskell
upsert :: (a -> Bool) -> (a -> a) -> a -> V.Vector a -> V.Vector a
alter :: (Maybe v -> Maybe v) -> k -> HashMap k v -> HashMap k v 
```

* Matching function `(a -> Bool)` is replaced by `k` (which is ok for hashmap, but vector can not match on keys)
* `(a -> a)` and `a` is replaced by `(Maybe v -> Maybe v)`. Instead of giving the two cases (update or insert) as two parameters to upsert, alter takes a function that must handle the case where none was found or one was found.
* Additionally alter has the feature of being able to delete the entry by giving `Nothing` has as it's value, which makes it a big more versatile.

I like what hashmap does here. When also using the feature of deleting the name "alter" makes more sense than update. So you could have for Vector:

```haskell
alter :: (Maybe a -> Maybe a) -> (a -> Bool) -> V.Vector a -> V.Vector a
```

What has been said so far about the downsides:

* This looks too specific for inclusion -> maybe how hashmap does it with addition of delete feature it's now multi purpose enough?
* Not often asked for -> On the other hand you can not measure how many times people have implemented similar patterns in their private code without raising a ticket.
* Not seem to benefit from fusion -> Other functions already indicate their slowness/speediness by big-O notation. Can do something similar here.

**Comment by Bodigrim** [comment]
I like `alter` more than `upsert`. Nevertheless, it is a typical example of a function, which works well with tree-like containers (`Map`, `HashMap` and PostgreSQL B-trees) and not so great with arrays. 

When you deal with a map, `alter` causes either update, or insert, or delete - and all three operations are O(log n) for maps. But for vectors it takes `O(n)` time and causes full re-allocation. Including such function into `vector` API would encourage people to use vectors, when they should be really using trees.

> On the other hand you can not measure how many times people have implemented similar patterns in their private code without raising a ticket.

The burden of proof is on the proposer

**Comment by Shimuuar** [comment]
There's general consensus that such function shouldn't be added. I'm closing it as wontfix
