### ISSUE TITLE
Nowhere seems to export the constructor to Storable vector

### ISSUE THREAD

**Issue by Boarders** [haskell/vector#343]
It would be nice if the internal module exported everything in the various modules and made no guarantees with regards to stability.

**Comment by Boarders** [comment]
More generally could we please move towards vector exporting everything somewhere. As it stands a user is not allowed to touch almost any aspect of the stream fusion framework. There is no particularly good reason for this if the relevant modules are marked unsafe and unstable.

**Comment by lehins** [comment]
You can already get to the internals of storable vector with unsafe to/from ForeignPtr convertors:
* [`unsafeFromForeignPtr`](https://hackage.haskell.org/package/vector-0.12.1.2/docs/Data-Vector-Storable.html#v:unsafeFromForeignPtr)
* [`unsafeTOForeignPtr`](https://hackage.haskell.org/package/vector-0.12.1.2/docs/Data-Vector-Storable.html#v:unsafeToForeignPtr)

Same applies to mutable vector

**Comment by Boarders** [comment]
I know, but if I want to copy and edit some internal vector code for doing streaming I am forced to jump through so many hoops like this and it seems completely needless.

**Comment by lehins** [comment]
> could we please move towards vector exporting everything somewhere.

Could you be more specific? Almost every aspect is already exported, including the stream fusion functionality. Maybe not as directly as it seems, but it is totally usable. In other words, could you compile a list of things you'd like to get access to that aren't available right now and we should be able to get them exported from some special module. Without such list we can't do anything because  "export everything" blindly is too messy of an approach, some things are really designed to be internal.
