### ISSUE TITLE
Revert #320, re-exports of primitive methods.

### ISSUE THREAD

**Issue by phadej** [haskell/vector#348]
Please revert that change. `vector` has very permissive bounds on `primitive`. The convenience argument is too light for this.

An alternative is to have strict `build-depends: primitive >=0.7.1 && <0.7.2`, otherwise `vector` would violate PVP. And given the importance of this package, I don' think it's a good idea.

**Comment by lehins** [comment]
I don't think I follow you strict bounds argument, especially the lower bound does not make sense. `PrimMonad` and `PrimState` has been around since vector-0.4, so almost as long as `vector` has been around and I don't think either one of them is going away in any forcible future.

But I do agree that we don't need re-exporting the actual `primitive` function from `PrimMonad` class, especially since `MonadPrim` has been added recently and it could potentially replace `PrimMonad` in the future. So I think re-export should be:
```haskell
import Control.Monad.Primitive ( PrimMonad, PrimState, RealWorld )
```

**Comment by phadej** [comment]
Ok. I think it's possible to write code against `vector` which would break depending on the underlying `primitive` version without new exports.

I'd be happy with not re-exporting `primitive`.

**Comment by phadej** [comment]
I'm worried that you won't not make https://pvp.haskell.org/#leaking-instances example worse. Especially as if users of `vector` would be able to omit `primitive` dependency. Then if `primitive` adds / removes instances, it **will be impossible** to make revisions if there are no primitive dependency. At least if they use something else than `IO` and `ST`.

**Comment by lehins** [comment]
I think user experience here is a lot more important than potential issue with instance removal that might never happen.

A user should be able to use mutable vector interface without even knowing about `primitive` package.

Moreover, `Prim` has always been re-exported, so that PVP argument is no longer relevant.

**Comment by phadej** [comment]
Maybe you should move `Prim` to re-exports sections too. To emphasize that it is not from `vector`.
