### ISSUE TITLE
Repository directory restructure

### ISSUE THREAD

**Issue by lehins** [haskell/vector#350]
We need a top level package folder `vector`. This has been a common practice for years, so its time to get vector to catch up.

**Comment by Shimuuar** [comment]
Is this to get `vector` and `vector-benchmarks` packages? Otherwise single-package repositories just live in repository root.

Such rename would cause a lot of pain for merging/rebasing for  all existing PR/branches. For what is essentially single-package repository benefits are minor and I think it just don't worth it
