### ISSUE TITLE
Not in scope: type constructor or class "PrimState"

### ISSUE THREAD

**Issue by wujilingfeng** [haskell/vector#367]
#### problem
My function's statement was written like "MVector (PrimState IO) Float",but there throw a error:" Not in scope: type constructor or class "PrimState" "。
#### details
 I want write a function to accepte a MVector, but the type name of MVector is too long.How do I write the function's statements?

**Comment by lehins** [comment]
@wujilingfeng This looks like a question rather than a bug report or a feature request. I do recommend going to [stackoverflow.com](https://stackoverflow.com/questions/tagged/haskell+vector) for asking questions like that.

`PrimState` is type family that is provided by `primitive` package, you can get it from there. Starting with version vector-0.13 it will also be re-exported from mutable modules, see #320, #348 and #351

If you still think that this is a bug, could you please reopen the ticket and provide some more information.
