### ISSUE TITLE
Data.Vector.Unboxed.Mutable and Data.Vector.Mutable not listed on Documentation page

### ISSUE THREAD

**Issue by stschiff** [haskell/vector#408]
I'm puzzled that two key modules, `Data.Vector.Unboxed.Mutable` and `Data.Vector.Mutable` are not listed on the front page of the Hackage documentation. Is there a good reason for that, or are they linked from other places? I couldn't find any.

**Comment by konsumlamm** [comment]
I'm not sure what you're talking sbout, they show up for me (https://hackage.haskell.org/package/vector-0.12.3.0). Maybe you're looking at an old version?

**Comment by lehins** [comment]
@konsumlamm Ironically these two modules are among the very few that have been available since the initial `vector-0.1`. :smile: 

@stschiff If I had to guess you might be talking about the fact that they are not listed in the `description` section of the cabal file:

https://github.com/haskell/vector/blob/f2339ea0c588f6e3c11c563c1cb1e2dcfc316e16/vector/vector.cabal#L20-L31

Well, none of the modules have to be listed there, moreover it is rather unusual to list them there. One way or another please provide more info next time when creating an issue. I'll close the ticket as invalid. In case that I misunderstood what you meant in this ticket, feel free to reopen it and provide more info or even better submit a PR.

**Comment by stschiff** [comment]
Ugh, I was stupid. Sorry... I wasn't even able to scroll down. I was confused by the whitespace below the description. My bad. And thanks for the great work behind that package!
