### ISSUE TITLE
Version tags seem to be missing.

### ISSUE THREAD

**Issue by erikd** [haskell/vector#496]
When running `git tag` in a checkout of this repo, that latest tag is `v0.12.3.1` but there are later version on Hackage.

Please upload all tags.

**Comment by erikd** [comment]
Have mailed the libraries mailing list https://mail.haskell.org/pipermail/libraries/2024-July/031664.html

**Comment by lehins** [comment]
Responded on the mailing list, but also responding here:

Starting with vector-0.13 we have two packages in the repository:

* vector-stream - which takes care of the streaming functionality and not necessarily
  vector specific
* vector - which is what the actual repo is about.

So, in order to disambiguate package releases starting with `vector-0.13.0.0` we also
include package names in the git tags. Here are both of the tags for both of the last
versions:

* https://github.com/haskell/vector/tree/vector-0.13.0.0
* https://github.com/haskell/vector/tree/vector-0.13.1.0
