### ISSUE TITLE
Add fmap/coerce rule(s)

### ISSUE THREAD

**Issue by treeowl** [haskell/vector#54]
`GHC.Base` has a rule to rewrite `map coerce` to `coerce`. This rule is valid and beneficial for any valid `Functor` instance, and should be added for the vector types.

**Comment by cartazio** [comment]
This may be tricky because of roles, but if we can do it, we should

**Comment by treeowl** [comment]
I forgot all about this. I should get to work :-D. Timing seems to be tricky because of stream fusion, which also involves lots of thing going on across lots of modules.

**Comment by cartazio** [comment]
did you ever make any headway on this?

**Comment by treeowl** [comment]
No, I never did. I found it extremely hard to find a place to fit such a
rule, since `vector` uses so many simplifier phases. Someone more familiar
with stream fusion might be able to figure it out, however. I'm much more
familiar with fold/build.

**Comment by cartazio** [comment]
ok, so closing for now, since i dont think we have the engineering resources to focus on this, and i suspect its not a bottleneck in anyones code at the moment. Not marking it as wont fix, unless you have reason to suspect it would greatly increase complexity of other folks using the fusion framework
