### ISSUE TITLE
Is it possible to allow returning a different Vector type?

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#66]
Currently the functions in `Data.Vector.Generic` always returns the same type of vector as the input. Is it possible to change it to return vectors of a different type? E.g., `map` over a `Storable` vector, returning a `Vector.Vector`, since the result of the map isn't `Storable`.

In other words, change the signature of 

    map :: (Vector v a, Vector v b) => (a -> b) -> v a -> v b

to

    map :: (Vector vi a, Vector vo b) => (a -> b) -> vi a -> vo b

**Comment by snoyberg** [comment]
I've wanted this in the past sometimes. I imagine an argument against it is that it might severely hurt type inference.

**Comment by dolio** [comment]
I suspect it would hurt type inference, yes.

We could include such an operation, but I'd like a name other than just `map`, since the current one corresponds well to `map` in almost every other library out there.

**Comment by Shimuuar** [comment]
It will. Consider following example: `map id . map id`. It will result ambiguous type error. First map produces result of type `Vector v a => v a`. GHC have no way to actually choose `v`. With current version same thing occurs with `convert . convert`

**Comment by yongqli** [comment]
Perhaps they could be put in a different module? Generic.Generic, perhaps? :P 

If I used convert on all the arguments will it fuse? Or will it result in wasteful copy to a different container type?

**Comment by cartazio** [comment]
a way around the inference problem would be to add a proxy arg

`mapTowards :: (Vector vi a, Vector vo b) => (a -> b) -> p vo -> vi a -> vo b `

i almost feel like the right api would be something a bit lensy.   

wrt fusion: if you can write the map Stream operation, it can fuse

**Comment by Shimuuar** [comment]
`convert` is basically `stream . unstream` so it should fuse. IMHO `convert` is good enough and adding another module only adds clutter to API.

I think real problem is that our functions wok with some internal representation of vectors which is different from manifest vector. And we cannot tell compiler that intermediate values should not appear at all.

**Comment by dolio** [comment]
Actually, I'm not sure if this is even worth having if you're going to talk about fusion. `mapTowards f` would just be a manual fusion of either `convert . map f` or `map f . convert` (both should fuse to the same thing).

**Comment by cartazio** [comment]
`convert` isn't strong enough.  you cant do `convert :: Data.Vector Text -> Data.Vector.Unboxed Text`

you need something like `mapThrough (length . unpack) :: Data.Vector Text -> Data.Vector.Unboxed  Int`

point being, `convert` is too weak/ not general  enought

**Comment by dolio** [comment]
If the output vector type is restricted to certain element types, you can convert after mapping instead of before.

And even in a situation where the valid element types between input and output are completely disjoint, you could in principle convert between a third vector type that allowed both (like boxed vectors). Assuming fusion works, it would be the same as `mapThrough`.

Only if fusion is not involved does the new combinator add power. Assuming fusion of `convert` does what I expect it does.

**Comment by cartazio** [comment]
oh yeah, you're absolutely right! my mistake, i now agree, `convert` is enough

**Comment by cartazio** [comment]
@dolio did we add convert in 0.11 or should we make that a 0.12 todo?

**Comment by Shimuuar** [comment]
`convert :: (Vector v a, Vector w a) => v a -> w a` was added a lo-o-ong time ago. It was present in 0.7

**Comment by cartazio** [comment]
@Shimuuar thanks! closing
