### ISSUE TITLE
Simulating mapAccumR is slow

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#71]
We've been simulating `mapAccumR` with something like (not tested):

    mapAccumR' f acc xs =
      map snd $ scanr' (\(acc, y) -> f acc) (acc, undefined) xs

In testing this is 6x slower for Storable vectors vs Unboxed vectors -- it seems that the intermediate vector is not optimized away. I'm guessing that with Unboxed, the vector representing the first part of the tuple is simply dropped, while for Storable it has to copy the first part of the intermediate list.

Any idea how to make it faster?

**Comment by JohnLato** [comment]
If you don't use `y` at all, does it help if you just unzip the vector first?

**Comment by yongqli** [comment]
Just tried it -- nope.

**Comment by cartazio** [comment]
a PR for implementing this would be welcome, but  for now since its not quite formulated as a clear feature request and we probably need to give our benchmark tooling some TLC before properly trying to address issues like this. 

likewise, different vector reps have different perf characteristics, thats not a bug :)
