### ISSUE TITLE
change in show instance in vector 0.10 vs 0.11

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#87]
in vector 0.10 and previous major versions

show was 

```
-- | Generic definition of 'Prelude.showsPrec'
showsPrec :: (Vector v a, Show a) => Int -> v a -> ShowS
{-# INLINE showsPrec #-}
showsPrec p v = showParen (p > 10) $ showString "fromList " . shows (toList v)
```

its now 

```
-- | Generic definition of 'Prelude.showsPrec'
showsPrec :: (Vector v a, Show a) => Int -> v a -> ShowS
{-# INLINE showsPrec #-}
showsPrec _ = shows . toList
```

granted, this makes the associated read instance a bit easier, but was this a deliberate change or something that no one noticed till now?

(i noticed it just now because it broke some tests in my hblas test suite)

@dolio @hvr  @ekmett

**Comment by cartazio** [comment]
original discussion https://github.com/haskell/vector/issues/14

**Comment by cartazio** [comment]
if nothing else, this change means that for some test suite codes i have, i actually need to use CPP to correctly have a test that works with 0.11 and <= 0.10 both

**Comment by glguy** [comment]
I changed some tests recently to use explicit equality to make the tests portable across new and old vector. This avoids needing CPP, but it's still unfortunate that it changed.

    >>> testcase
    fromList [1,2,3]

to

    >>> testCase == fromList [1,2,3]
    True

**Comment by cartazio** [comment]
@dolio @glguy i think the root issue for this ticket is about pretty printing vs debug oriented rendering, and while the conclusion here isn't wrong, i'm not sure if its the right end story for vector, nor a sensible end state.  I think we should revisit this for 0.12

**Comment by dolio** [comment]
I'm somewhat reluctant to change the show instance back, because it might just cause more people to have to fix things again, but I must admit I'm not a huge fan of the current one.

One thing to note is that `OverloadedLists` wasn't even added until GHC 7.8. So on 7.6 and 7.4 (which are still listed as supported), the shown text can't even be legal notation for a vector.

It also seems like it might be useful to be able to tell what sort of vector is being shown, if we made the `Show` instance more informative than `fromList [...]`, possibly by adding vector-specific `fromList` functions for the purpose.

**Comment by ekmett** [comment]
I think ultimately the pain has already been borne to get us the new instance and any reversion would just prolong and further complicate the situation leaving us with the uglier old instance anyways.

**Comment by Shimuuar** [comment]
Instances are around for quite some time and everyone got used to them. Now there's noreason to change anything. I think we should just close this issue

**Comment by cartazio** [comment]
Yeah.  We could still provide some alternative printers at some point etc
etc

**Comment by Shimuuar** [comment]
So I'm closing it. We don't have any requests about pretty-printers anyway
